version: 1

dataset:
  name: "Python Comment Evolution Dataset"
  description: >
    Repositories selected for a study of Python commenting practices
    across two time periods.
  theme: "cli-tools"
  groups:
    old_2000s:
      label: "2000s"
    new_2020s:
      label: "2020s"

repos:
  - name: "pip"
    url: "https://github.com/pypa/pip"
    group: "old_2000s"
    release: "1.0.1"
  - name: "virtualenv"
    url: "https://pypi.org/project/virtualenv/"
    group: "old_2000s"
    release: "1.4"
    notes: "Some source files in the release are compressed, so we will have to uncompress them"
  - name: "setuptools"
    url: "https://pypi.org/project/setuptools/"
    group: "old_2000s"
    release: "0.6c11"
  - name: "scons"
    url: "https://github.com/SCons/scons"
    group: "old_2000s"
    release: "1.0.0"
  - name: "coverage"
    url: "https://pypi.org/project/coverage/"
    group: "old_2000s"
    release: "3.0"
  - name: "nose"
    url: "https://github.com/nose-devs/nose"
    group: "old_2000s"
    release: "0.11.1"
  - name: "pygments"
    url: "https://pypi.org/project/Pygments/"
    group: old_2000s
    release: "1.0"
  - name: "ipython"
    url: "https://pypi.org/project/ipython/"
    group: "old_2000s"
    release: "0.10.1"

  - name: "pip-audit"
    url: "https://github.com/pypa/pip-audit"
    group: "new_2020s"
    release: "2.9.0"
  - name: "typer"
    url: "https://github.com/fastapi/typer"
    group: "new_2020s"
    release: "0.19.0"
  - name: "pdm"
    url: "https://github.com/pdm-project/pdm"
    group: "new_2020s"
    release: "2.26.0"
  - name: "textualize"
    url: "https://github.com/Textualize/textual"
    group: "new_2020s"
    release: "1.0.0"
  - name: "rich"
    url: "https://github.com/Textualize/rich"
    group: "new_2020s"
    release: "14.0.0"
  - name: "build"
    url: "https://github.com/pypa/build"
    group: "new_2020s"
    release: "1.4.0"
  - name: "poetry-plugin-export"
    url: "https://github.com/python-poetry/poetry-plugin-export"
    group: "new_2020s"
    release: "1.10.0"
  - name: "pytask"
    url: "https://pypi.org/project/pytask/"
    group: "new_2020s"
    release: "0.5.8"
